baseURL = "https://www.zerotoasiccourse.com/"
languageCode = "en-us"
title = "Zero to ASIC Course"
theme = "ananke"

[params]
  site_logo = "/zero-to-asic-logo-white-transp.png"
  favicon = "/zero-to-asic-logo-transp.png"
  stripe_test = "false"
  description = "Learn how to make your own chips!"
  title = "Zero to ASIC Course"
  images = ["zero-to-asic-logo-white-bg.png"]

[menu]

[[menu.main]]
identifier = "Terminology"
name = "Terminology"
url = "/terminology"
weight = 40

[[menu.main]]
identifier = "Articles"
name = "Articles"
url = "/post"
weight = 20

[[menu.main]]
identifier = "Interviews"
name = "Interviews"
url = "/interviews"
weight = 30

[[menu.main]]
identifier = "Matt Venn"
name = "Matt Venn"
url = "/matt_venn"
weight = 40

[[menu.main]]
identifier = "Buy a ticket"
name = "Buy a ticket"
url = "/contact"
weight = 45
[menu.main.params]
      class = "button"

[[menu.main]]
identifier = "Newsletter"
name = "Newsletter"
url = "/newsletter"
weight = 20

[[menu.main]]
identifier = "Resources"
name = "Resources"
url = "/resources"
weight = 20
