baseURL = "https://www.zerotoasiccourse.com/"
languageCode = "en-us"
title = "Zero to ASIC Course"
theme = "ananke"

[params]
  site_logo = "/zero-to-asic-logo-white-transp.png"
  favicon = "/zero-to-asic-logo-transp.png"

[menu]

[[menu.main]]
identifier = "Terminology"
name = "Terminology"
url = "/terminology"
weight = 10

[[menu.main]]
identifier = "Articles"
name = "Articles"
url = "/post"
weight = 10

[[menu.main]]
identifier = "Interviews"
name = "Interviews"
url = "/interviews"
weight = 10

[[menu.main]]
identifier = "Buy a ticket"
name = "Buy a ticket"
url = "/contact"
weight = 1

[[menu.main]]
identifier = "Newsletter"
name = "Newsletter"
url = "/newsletter"
weight = 2
