name: tweet-a-term
on: workflow_dispatch
jobs:
  tweet-a-term:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7' # install the python version needed

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"

    - name: run tweet a term
      run: python ./tweet_a_term.py

